package rerules
import ss.pku.re.domain.Event;
import ss.pku.re.rule.util.domain.Service;
import ss.pku.re.rule.util.DIAServiceManager;
query 'query fact'(String id)
event:Event(eventId==id)
end
rule'rule_Scene1_rule'
when
Context5:Event(eventId.equals('Context5'),values[0]==100,getTimes(3,5)==3)

then
Service service= new Service();
service.setServiceId('Service1');
service.setValue('HelloWord!');
DIAServiceManager.sendService(service);
 end
