package rerules
import ss.pku.re.domain.Event;
import ss.pku.re.rule.util.domain.Service;
import ss.pku.re.rule.util.DIAServiceManager;
query 'query fact'(String id)
event:Event(eventId==id)
end
rule'rule_Scene1_rule'
when
Context6:Event(eventId.equals('Context6'))
Context7:Event(eventId.equals('Context7'),values[0]>0,checkTime(Context6.getReceivedTime(),100000.0,'<')==true)

then
Service service= new Service();
service.setServiceId('Service1');
service.setValue('HelloWord!');
DIAServiceManager.sendService(service);
 end
